# Generated by Django 5.0.6 on 2026-03-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_article_keywords_alter_article_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newssource',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='processinglog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
