# Generated by Django 5.0.6 on 2026-03-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_newssource_id_alter_processinglog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='keywords',
            field=models.CharField(max_length=250),
        ),
    ]
